'use client';
import dynamic from 'next/dynamic';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,AudioLines,BrainCircuit,Camera,ChevronRight,CircleHelp,Download,Expand,MapPin,Mic,MicOff,MoveUpRight,Octagon,Play,RotateCcw,ShieldCheck,Terminal,Volume2,X,Layers,Command,Activity,Eye} from 'lucide-react';
import type {Snapshot} from '../types';
import {KeyboardControls} from '../components/KeyboardControls';
import {useMicrophone} from '../components/useMicrophone';
const Scene=dynamic(()=>import('../components/Scene'),{ssr:false});
const format=(ms:number|null)=>ms===null?'—':ms<10?ms.toFixed(1):Math.round(ms).toString();
export default function Home(){
 const [s,setS]=useState<Snapshot|null>(null),[connected,setConnected]=useState(false),[reality,setReality]=useState(false),[tab,setTab]=useState('perception'),[text,setText]=useState(''),[localError,setLocalError]=useState(''),[about,setAbout]=useState(false),[speaking,setSpeaking]=useState(false);
 const socket=useRef<WebSocket|null>(null),canvas=useRef<HTMLCanvasElement|null>(null),reconnect=useRef<ReturnType<typeof setTimeout>|null>(null);
 const send=useCallback((m:unknown)=>{if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify(m));else setLocalError('Runtime disconnected. Reconnecting…');},[]);
 const mic=useMicrophone(send);const micRef=useRef(mic);micRef.current=mic;
 useEffect(()=>{
  let disposed=false;
  function connect(){const ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`);socket.current=ws;ws.onopen=()=>{setConnected(true);setLocalError('');};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='snapshot')setS(m.state);if(m.type==='gradium_ready')micRef.current.begin();if(m.type==='gradium_closed')micRef.current.stop(false);if(m.type==='voice_audio')micRef.current.play(m.audio,m.sampleRate);};ws.onclose=e=>{micRef.current.stop(false);setConnected(false);if(e.code===1008){setLocalError('Another operator controls this robot. Close that tab first.');return;}if(!disposed)reconnect.current=setTimeout(connect,2000);};}
  connect();const timer=setInterval(()=>send({type:'heartbeat'}),400);
  return()=>{disposed=true;clearInterval(timer);if(reconnect.current)clearTimeout(reconnect.current);socket.current?.close();};
 },[send]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea'))return;if(e.key.toLowerCase()==='r'){window.dispatchEvent(new CustomEvent('cortex-inspect',{detail:false}));setReality(v=>!v);}if(e.code==='Space'){e.preventDefault();send({type:'stop'});}if(e.key==='Escape')setReality(false);};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[send]);
 const p=s?.policy,v=s?.vocal,robot=s?.robot;const phase=!connected?'CONNECTING':s?.phase??'STARTING';const error=localError||s?.error;
 const capture=()=>{if(!canvas.current)return;try{send({type:'capture',image:canvas.current.toDataURL('image/png')});}catch{setLocalError('Camera frame capture failed.');}};
 const startMic=async()=>{setLocalError('');try{if(mic.listening)mic.stop();else await mic.prepare();}catch(e){setLocalError(e instanceof Error?e.message:String(e));}};
 const speak=()=>send({type:'speak_response'});
 return <main className={reality?'app reality':'app'}>
  <header className="header">
   <a className="brand" href="/"><span className="brand-mark"><i/><i/><i/></span>CORTEX<span className="brand-caption">PHYSICAL INTELLIGENCE</span></a>
   <nav><button className="nav-active">Control room</button><a href="/pitch.html" target="_blank">The pitch <ArrowUpRight size={12}/></a><button onClick={()=>setAbout(true)}>About <ArrowUpRight size={12}/></button></nav>
   <div className="header-status"><span className={connected?'dot':'dot off'}/>{connected?'RUNTIME CONNECTED':'CONNECTING'}<span className="version">v0.1</span></div>
  </header>
  <section className="workspace-heading">
   <div><div className="eyebrow">ROBOT OPERATING SYSTEM <span>/</span> SESSION 001</div><h1>A little more human.</h1><p>Words give the instruction. Voice changes the way.</p></div>
   <div className="mode-switch"><button className="selected"><BrainCircuit size={15}/>Cortex</button><button onClick={()=>{window.dispatchEvent(new CustomEvent('cortex-inspect',{detail:false}));setReality(true);}}><Expand size={14}/>Reality <kbd>R</kbd></button></div>
  </section>
  <section className="control-grid">
   <div className="world-column">
    <div className="viewport">
     <Scene robot={robot??null} onCanvas={c=>{canvas.current=c;}}/>
     <div className="view-top"><span><span className="dot"/> {robot?'LIVE SIMULATION':'CONNECTING TO SIMULATOR'}</span><button title="Inspect 3D scene" onClick={()=>window.dispatchEvent(new CustomEvent('cortex-inspect'))}><Layers size={16}/></button><button title="60° orbit view" onClick={()=>window.dispatchEvent(new CustomEvent('cortex-view-angle'))}>60°</button><button title="Reality mode" onClick={()=>{window.dispatchEvent(new CustomEvent('cortex-inspect',{detail:false}));setReality(true);}}><Expand size={16}/></button></div>
     <div className="location-stamp"><MapPin size={14}/><span>Painted Ladies · Alamo Square<small>{process.env.NEXT_PUBLIC_SPLAT_MANIFEST?'SAN FRANCISCO, CA · RECONSTRUCTION ASSET':'SAN FRANCISCO, CA · FULL 3D ARCHITECTURAL STUDY'}</small></span></div>
     <div className="camera-stamp"><Camera size={13}/> CAM 01 <span>G1 / MUJOCO</span></div>
     {!robot&&<div className="robot-offline">Robot controller offline<small>Start the MuJoCo server on port 8002.</small></div>}
     <button className="reality-exit" onClick={()=>setReality(false)}>CORTEX <Layers size={15}/><kbd>R</kbd></button>
    </div>
    <div className="telemetry-strip"><div><span className={'status-orb '+(phase==='MOVING'?'moving':'')}/><span className="phase">{phase}</span></div><div><span className="meta-label">VELOCITY</span><b>{robot?robot.velocity.toFixed(2):'—'} <small>m/s</small></b></div><div><span className="meta-label">TARGET</span><b>{robot?.currentWaypoint??'HOME'}</b></div><div><ShieldCheck size={16}/><span className="safety-label">Safety governor <b>{robot?.estop?'STOP LATCHED':'ACTIVE'}</b></span></div></div>
    <KeyboardControls send={send} connected={connected&&!!robot} latched={!!robot?.estop}/>
    <div className="voice-console">
     <div className="voice-row"><div className="waveform">{Array.from({length:34},(_,i)=><i key={i} style={{height:mic.listening?`${5+mic.level*30*(.3+Math.abs(Math.sin(i*1.7)))}px`:`${Math.round(4+Math.abs(Math.sin(i*.8))*12)}px`,opacity:mic.listening?1:.35}}/>)}</div><span>{mic.listening?'Listening through Pipecat':'YOUR VOICE IS THE INTERFACE'}</span><span className="audio-label">{mic.listening?'MIC LIVE':'MIC OFF'}</span></div>
     <div className="transcript">{s?.inputSource==='KEYBOARD'?'Keyboard control':v?`“${v.transcript}”`:'“Come here.”'}<span>{s?.inputSource==='KEYBOARD'?'SHARED MOTION TOOLS · ROBOT-RELATIVE DIRECTIONS':v?(s?.inputSource==='TYPED'?'TYPED COMMAND · NO VOCAL EXPRESSION':s?.mode==='DEMO'?'DEMO INPUT · SYNTHETIC ACOUSTIC FIXTURE':'GRADIUM STT · LOCAL ACOUSTIC CUES'):'SAME WORDS. DIFFERENT POSSIBILITIES.'}</span></div>
     <div className="voice-controls"><button className={'primary '+(mic.listening?'recording':'')} onClick={startMic}>{mic.listening?<MicOff size={16}/>:<Mic size={16}/>} {mic.listening?'End microphone':'Connect microphone'}<span>↗</span></button><button className="stop-button" onClick={()=>send({type:'stop'})}><Octagon size={15}/>Stop <kbd>SPACE</kbd></button><button className="outline" disabled={!robot?.estop} onClick={()=>send({type:'resume'})}>Resume</button><button className="icon-button" title="Reset simulation" onClick={()=>send({type:'reset'})}><RotateCcw size={16}/></button></div>
    </div>
    <div className="demo-row"><span className="eyebrow">TRY THE SAME WORDS <span className="fixture-tag">DEMO</span></span><div><button onClick={()=>send({type:'fixture',name:'calm'})}><span className="mini-wave">▁▃▂▁</span>Calm voice</button><button onClick={()=>send({type:'fixture',name:'urgent'})}><span className="mini-wave">▃▇▅▇</span>Urgent voice</button><button onClick={()=>send({type:'fixture',name:'fearful'})}>Hesitant voice</button><button title="Replay stop voice fixture" onClick={()=>send({type:'fixture',name:'stop'})}>Wait! Stop!</button></div><small>Reset between runs to compare the same starting position.</small></div>
   </div>
   <aside className="inspector">
    <div className="inspector-tabs">{['perception','memory','trace'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='perception'?'Perception':t==='memory'?'Visual memory':'Event trace'}{t==='trace'&&<span>{s?.traces.length??0}</span>}</button>)}</div>
    {tab==='perception'&&<>
     <section className="inspector-section gradium-section"><div className="section-heading"><span className="eyebrow">01 / HEAR THE HUMAN</span><span className="provider-word">gradium<span className="dot"/></span></div><h2>Beyond the transcript.</h2><p>Gradium speech. Pipecat turns. Local acoustic cues.</p><div className="signal-label"><span>LOCAL ACOUSTIC CUES</span><span>{s?.providers.GRADIUM.mode??'DEMO'}</span></div>
      <div className="expression-bars">{(v?.expressions.slice(0,5)??['Vocal intensity','Pitch movement','Pause fraction'].map(name=>({name,score:0}))).map(e=><div className="expression" key={e.name}><span>{e.name}</span><div className="bar-track"><i style={{width:`${e.score*100}%`}}/></div><b>{v?e.score.toFixed(2):'—'}</b></div>)}</div>
      <div className="derived"><div><span>URGENCY</span><b>{v?v.derived.urgency.toFixed(2):'—'}</b></div><div><span>HESITATION</span><b>{v?v.derived.hesitation.toFixed(2):'—'}</b></div><div><span>CALMNESS</span><b>{v?v.derived.calmness.toFixed(2):'—'}</b></div></div><small className="note">Local heuristics, not Gradium emotion classifications.</small><details className="signal-details"><summary>Measured acoustics &amp; policy cues</summary><pre>{JSON.stringify({acoustics:v?.acoustics??null,cues:v?.expressions??[],derived:v?.derived??{}},null,2)}</pre></details>
     </section>
     <section className="inspector-section policy-section"><div className="section-heading"><span className="eyebrow">02 / CHANGE THE BEHAVIOR</span><MoveUpRight size={16}/></div><h2>Voice → motion</h2><dl className="policy-list"><div><dt>Mission priority</dt><dd className="accent">{p?(p.priority>.8?'HIGH':p.priority>.5?'ELEVATED':'NORMAL'):'NORMAL'} <small>{p?.priority.toFixed(2)??'.40'}</small></dd></div><div><dt>Walking speed limit</dt><dd>{p?.maxSpeed.toFixed(2)??'0.55'} <small>m/s</small></dd></div><div><dt>Final approach</dt><dd>{p?.approachSpeed.toFixed(2)??'0.35'} <small>m/s</small></dd></div><div><dt>Personal space</dt><dd>{p?.personalSpaceMeters.toFixed(1)??'1.2'} <small>meters</small></dd></div><div><dt>Confirmation</dt><dd>{p?.requireConfirmation?'REQUIRED':'NOT REQUIRED'}</dd></div></dl><div className="safety-note"><ShieldCheck size={13}/> Voice never overrides safety.</div></section>
    </>}
    {tab==='memory'&&<section className="inspector-section memory-section"><div className="section-heading"><span className="eyebrow">EPISODIC VISUAL MEMORY</span><Eye size={16}/></div><h2>A place to remember.</h2><p>Capture a scene frame, then retrieve its sighting.</p>{s?.memory?<div className="memory-evidence"><img src={s.memory.evidence} alt="Stored scene evidence showing the backpack near the planter"/><span>{s.memory.source} · OPERATOR-LABELED SIGHTING</span><h3>Backpack</h3><dl className="policy-list"><div><dt>Last seen</dt><dd>Planter</dd></div><div><dt>Recorded at</dt><dd>{new Date(s.memory.timestamp).toLocaleTimeString()}</dd></div><div><dt>Evidence</dt><dd><a href={s.memory.evidence} target="_blank">Open frame ↗</a></dd></div></dl></div>:<div className="memory-empty"><Camera size={30}/><p>No sighting stored yet.</p><small>Save the visible backpack scene to create evidence.</small></div>}<button className="outline full" onClick={capture}><Camera size={15}/>Capture scene memory</button><button className="outline full" onClick={()=>send({type:'fixture',name:'memory'})}>Where did you see my backpack? <ChevronRight size={14}/></button>{s?.mode==='DEMO'&&s.providers.GRADIUM.mode!=='LIVE'&&<button className="outline full" onClick={()=>send({type:'fixture',name:'anxious_memory'})}>I really need my backpack <span className="fixture-tag">DEMO</span></button>}<button className="primary full" onClick={()=>send({type:'text',text:'Take me there.'})}>Take me there <MoveUpRight size={15}/></button></section>}
    {tab==='trace'&&<section className="inspector-section trace-section"><div className="section-heading"><span className="eyebrow">COGNITION, IN THE OPEN</span><a href="/api/traces" title="Download trace"><Download size={15}/></a></div><h2>Every decision has a path.</h2><details className="signal-details"><summary>Structured mission plan</summary><pre>{JSON.stringify(s?.plan??[],null,2)}</pre></details><details className="signal-details"><summary>All measured latency values</summary><div className="all-metrics">{s?.metrics.map(m=><p key={m.name}>{m.name}<b>{format(m.ms)} ms</b></p>)}</div></details><div className="trace-list">{s?.traces.length?s.traces.map(t=><div key={t.id}><time>{new Date(t.at).toLocaleTimeString('en-US',{hour12:false})}</time><span><b>{t.component}</b><p>{t.message}</p></span></div>):<p className="note">Your first command will appear here.</p>}</div></section>}
    <div className="robot-response"><span className="response-icon"><AudioLines size={18}/></span><div><span className="eyebrow">CORTEX</span><p>{s?.response??'Ready when you are.'}</p></div><button onClick={speak} title="Speak response using Gradium" className={speaking?'accent':''}><Volume2 size={16}/></button></div>
   </aside>
  </section>
  {s?.pendingConfirmation&&<div className="confirmation"><ShieldCheck size={20}/><div><b>Holding a little more space.</b><p>Pauses triggered a cautious approach. Confirm to proceed.</p></div><button className="primary" onClick={()=>send({type:'confirm'})}>Yes, approach</button><button className="outline" onClick={()=>send({type:'stop'})}>Stay there</button></div>}
  {error&&<div className="error-banner"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>{setLocalError('');setS(old=>old?{...old,error:null}:old);}}><X size={15}/></button></div>}
  <section className="inference-story"><span className="eyebrow">Inference · SambaNova</span><p>Agent inference runs on SambaNova RDU dataflow infrastructure—built for responses in conversation time.</p><span>Voice · Gradium <i>/</i> Orchestration · Pipecat</span></section><section className="bottom-grid">
   <div className="pipeline"><div className="section-heading"><span className="eyebrow">ONE CONNECTED NERVOUS SYSTEM</span><button className="text-button" onClick={()=>send({type:'healthcheck'})}>Run healthcheck <ArrowUpRight size={12}/></button></div><div className="provider-flow">{Object.entries(s?.providers??{GRADIUM:{mode:'DEMO',active:false},SAMBA:{mode:'DEMO',active:false},MEMORIES:{mode:'DEMO',active:false},JEV:{mode:'LOCAL',active:false},EDGEONE:{mode:'LOCAL',active:false},ROBOT:{mode:'OFFLINE',active:false}}).map(([name,provider],i)=><div key={name}><span className={'provider-node '+(provider.active?'lit':'')}><span className={'dot '+(provider.mode==='OFFLINE'?'off':'')}/>{name}</span><small>{provider.mode}</small>{i<Object.keys(s?.providers??{}).length-1&&<ChevronRight className="flow-arrow" size={12}/>}</div>)}</div><form className="text-command" onSubmit={e=>{e.preventDefault();if(text.trim()){send({type:'text',text});setText('');}}}><Terminal size={14}/><input value={text} onChange={e=>setText(e.target.value)} placeholder="Or type a command… (no vocal expression)"/><button type="submit" aria-label="Send command"><MoveUpRight size={16}/></button></form></div>
   <div className="latency"><div className="section-heading"><span className="eyebrow">MEASURED, NEVER INVENTED</span><Activity size={14}/></div><div className="latency-values">{(s?.metrics??[]).filter(m=>['Transcript → reflex','Command → acknowledgement','Stop → settled'].includes(m.name)).map(m=><div key={m.name}><b>{format(m.ms)}<small>ms</small></b><span>{m.name}</span></div>)}</div><small className="note">{s?.mode==='DEMO'?'Fixture input · live MuJoCo timing · no speech latency claim':'Server arrival timestamps · microphone buffering excluded'}</small></div>
  </section>
  <footer><span>CORTEX <i> / </i> Same words. Different voice. Different physical policy.</span><span>G1 physics · 3D Painted Ladies study · <button onClick={()=>setAbout(true)}>View provenance <ArrowUpRight size={11}/></button></span></footer>
  {about&&<div className="modal-backdrop" onClick={()=>setAbout(false)}><section className="about-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAbout(false)}><X/></button><span className="eyebrow">CORTEX / BUILD NOTES</span><h2>Feel the difference.<br/>Inspect the evidence.</h2><p>This is a working MuJoCo simulation using Unitree’s frozen G1 walking controller. The robot view follows actual simulated joints and contacts.</p><p>The Painted Ladies are now a full-depth architectural study with modeled bays, roofs, side walls, stairs and windows. Geometry and park placement are authored approximations, not a surveyed digital twin. The earlier partial jtressle scan remains bundled as reference. Photorealism acceptance is still open.</p><p>DEMO acoustic cues are synthetic fixtures. Gradium supplies speech recognition and synthesis; acoustic heuristics are local, not emotion diagnoses. LIVE appears only after a provider responds. Scene memories are actual captured frames with operator-supplied object and waypoint labels; no automated visual recognition is claimed.</p><p><a href="https://sketchfab.com/3d-models/san-francisco-painted-ladies-cf5aeb7fb0ac4152b43f72ce1dac60d6" target="_blank">3D scan: jtressle · CC BY 4.0 ↗</a></p><div className="about-links"><a href="/pitch.html" target="_blank">Five-slide pitch ↗</a><a href="/api/traces">Export trace ↗</a></div><span className="note">WASD / arrows: walk · Q/E: turn · R: modes · Space: stop</span></section></div>}
 </main>;
}
