import {chromium} from '@playwright/test';
import {mkdir,writeFile,copyFile,readFile} from 'node:fs/promises';
await mkdir('.data/video',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});const context=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir:'.data/video',size:{width:1440,height:900}},deviceScaleFactor:1});const page=await context.newPage();
const indian=JSON.parse(await readFile('public/media/chapters-indian.json','utf8'));
const chapters=[];let started=Date.now();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const delay=ms=>page.waitForTimeout(ms);
async function state(){return page.evaluate(()=>fetch('/api/status').then(r=>r.json()));}
async function until(fn,ms=15000){const at=Date.now();while(!await fn()){if(Date.now()-at>ms)throw Error('Recording assertion timeout: '+JSON.stringify(await state()));await delay(100);}}
async function click(text){await page.evaluate(text=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()===text||b.textContent?.trim().endsWith(text)||b.textContent?.trim().startsWith(text));if(!button)throw Error('Button not found: '+text);button.click();},text);}
async function reset(){const old=(await state()).traces.find(t=>t.message==='reset() · HOME')?.id;await page.getByTitle('Reset simulation').evaluate(b=>b.click());await until(async()=>{const s=await state();return s.traces.find(t=>t.message==='reset() · HOME')?.id!==old&&s.robot?.status==='idle'&&!s.robot?.estop;});}
async function caption(title,sub,narration){narration=indian.chapters[chapters.length]?.narration??narration;const start=(Date.now()-started)/1000;chapters.push({start,title,sub,narration});await page.evaluate(({title,sub})=>{let el=document.getElementById('film-caption');if(!el){el=document.createElement('div');el.id='film-caption';document.body.append(el);}el.innerHTML='';Object.assign(el.style,{position:'fixed',bottom:'25px',left:'34px',zIndex:'100',background:'#101a12ec',color:'#edf4e2',padding:'16px 24px',borderLeft:'3px solid #d6ed9c',fontFamily:'Arial,sans-serif',maxWidth:'900px',pointerEvents:'none'});const h=document.createElement('div');h.textContent=title;h.style.cssText='font-size:25px;letter-spacing:-.6px';const p=document.createElement('div');p.textContent=sub;p.style.cssText='font-size:10px;color:#afc09d;margin-top:8px;letter-spacing:.5px';el.append(h,p);}, {title,sub});}
try{
 await page.goto(process.env.CORTEX_TEST_URL??'http://localhost:3000',{waitUntil:'networkidle'});await until(async()=>!!(await state()).robot);await page.waitForFunction(()=>Number(document.querySelector('canvas')?.dataset.architectureVertices)>100000);await page.getByRole('button',{name:'Perception',exact:true}).click();await delay(1200);
 await page.addStyleTag({content:'.app:not(.reality){zoom:.76}.app:not(.reality) .workspace-heading{padding:18px 0}.app:not(.reality) .viewport{height:360px}.app:not(.reality) .header{height:65px}.app:not(.reality) .inspector-section{padding:17px 23px}.app:not(.reality) .voice-console{padding:17px 23px}.reality .reality-exit{display:none!important}'});
 await reset();await page.keyboard.press('r');await delay(700);started=Date.now();
 await caption('CORTEX','WORKING PROTOTYPE · SYNTHETIC ACOUSTIC INPUT · LIVE MUJOCO SIMULATION','This is Cortex. This recording uses synthetic vocal profiles to drive a real MuJoCo simulation. The robot is simulated, and the Painted Ladies are modeled architecture in a three dimensional park scene. This is an architectural study, not a photoreal digital twin.');await delay(11000);
 await caption('Step into the scene.','FULL-DEPTH ARCHITECTURE · MODELED PARK · CAMERA PARALLAX','The camera moves around modeled Painted Ladies. The buildings have side walls, roofs, projecting windows, stairs and geometric depth. A modeled Alamo Square path gives the robot a bounded walking area.');await page.evaluate(()=>window.dispatchEvent(new CustomEvent('cortex-inspect',{detail:true})));await page.mouse.move(720,450);await page.mouse.down();await page.mouse.move(850,490,{steps:35});await page.mouse.up();await delay(6500);await page.evaluate(()=>window.dispatchEvent(new CustomEvent('cortex-inspect',{detail:false})));
 await reset();await caption('One set of tools. Keyboard or voice.','HOLD W / A / S / D · Q / E TURN · SPACE STOPS','Keyboard and voice share the same tools. Hold a direction: the robot turns first, then walks. Release to pause. Named targets pass through planning and the reflex gate.');await page.keyboard.down('a');await delay(4800);await page.keyboard.up('a');await delay(4000);
 await reset();await caption('“Come here.”','CALM PROFILE · 0.55 M/S SPEED CEILING · NORMAL APPROACH','First, the calm profile. Come here. The robot approaches at a moderate pace, with a comfortable stopping distance.');await click('Calm voice');await until(async()=>(await state()).robot.status==='moving');await delay(9500);
 await reset();await caption('“Come here.”','IDENTICAL TRANSCRIPT · URGENT PROFILE · 0.90 M/S SPEED CEILING','Reset. Exactly the same words, with a higher-intensity acoustic profile. Priority rises and the walking policy changes. The feet are driven by Unitree’s frozen locomotion controller.');await click('Urgent voice');await until(async()=>(await state()).robot.status==='moving');await delay(10000);
 await page.keyboard.press('r');await page.evaluate(()=>scrollTo(0,0));await caption('Same words. Different voice. Different physical policy.','LOCAL ACOUSTIC CUES · GRADIUM + PIPECAT VOICE → DOCUMENTED MAPPING → SAFETY GOVERNOR → G1','Reveal Cortex. Measured acoustic cues become a documented behavioral policy. Speed, approach distance and confirmation are explicit. The live microphone path is implemented through Gradium and Pipecat.');await delay(10500);
 await reset();await click('Hesitant voice');await until(async()=>(await state()).pendingConfirmation);await caption('Hesitation changes the response, too.','CAUTIOUS APPROACH · 2.0 M PERSONAL SPACE · CONFIRMATION REQUIRED','A hesitant acoustic profile does not simply make the robot faster. It holds for confirmation, reduces approach speed, and gives the person more space.');await delay(7000);await click('Stay there');
 await reset();await click('Visual memory');await click('Capture scene memory');await until(async()=>!!(await state()).memory);await click('Where did you see my backpack?');await until(async()=>/I saw it beside the planter/.test((await state()).response));await caption('“Where did you last see my backpack?”','ACTUAL CAPTURED FRAME · OPERATOR-LABELED LOCAL MEMORY · PLANTER','Now memory. Save the scene, then ask where the backpack was seen. Cortex retrieves the actual captured frame and its registered location, beside the planter.');await delay(9500);
 await click('Take me there');await until(async()=>(await state()).robot.status==='moving');await page.keyboard.press('r');await caption('“Take me there.”','RETRIEVED EVIDENCE → REGISTERED WAYPOINT → PHYSICAL NAVIGATION','Take me there. The retrieved sighting becomes a waypoint, and the robot turns toward the planter.');await delay(6000);
 await caption('“WAIT! STOP!”','FAST REFLEX PATH · NO PLANNER ROUND TRIP','Wait. Stop. The reflex bypasses the planner, latches the stop, and measures acknowledgement and physical settling separately.');await page.getByTitle('Replay stop voice fixture').evaluate(b=>b.click());await until(async()=>(await state()).robot.status==='idle'&&(await state()).response==='Stopped.');await delay(3000);await page.keyboard.press('r');await click('Event trace');await delay(6500);
 await caption('“Continue, but slowly.”','CONTINUE THE JOURNEY · REDUCED 0.30 M/S SPEED CEILING','Continue, but slowly. A deliberate resume releases the stop and applies a lower speed ceiling. Vocal delivery can change behavior. It can never turn safety off.');await page.locator('input').fill('Continue, but slowly.');await page.locator('input').press('Enter');await page.locator('input').evaluate(e=>e.blur());await until(async()=>(await state()).robot.status==='moving');await page.keyboard.press('r');await delay(8000);
 await page.keyboard.press('Space');await caption('CORTEX · Hear the human behind the instruction.','GRADIUM · PIPECAT · SAMBANOVA · MUJOCO · SOURCE, TESTS & PITCH INCLUDED','Cortex gives physical AI perception, memory, reasoning, reflexes, and safe action. Gradium handles voice, Pipecat carries the conversation, and SambaNova plans the next safe action.');await delay(10500);
 if(errors.length)throw new Error('Browser errors during capture: '+errors.join('; '));
 const duration=(Date.now()-started)/1000;const manifest={duration,chapters,errors,narration:{voice:'Rishi',locale:'en-IN',provider:'macOS system speech',generated:true},provenance:'Actual application; synthetic acoustic fixtures; live MuJoCo; system-generated narration; Authored Painted Ladies architectural approximation and Alamo Square foreground; no photorealism claim'};await writeFile('public/media/chapters.json',JSON.stringify(manifest,null,2));await writeFile('public/media/chapters-indian.json',JSON.stringify(manifest,null,2));
 const rawPath=await page.video().path();await context.close();await copyFile(rawPath,'public/media/CORTEX-demo-raw.webm');console.log(JSON.stringify({duration,chapters:chapters.length,rawPath,errors}));
}finally{await browser.close();}
