import {chromium,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
async function state(){return page.evaluate(()=>fetch('/api/status').then(r=>r.json()))}
async function reset(){const before=(await state()).traces.find(t=>t.message==='reset() · HOME')?.id;await page.getByTitle('Reset simulation').click();await until(async()=>{const s=await state();return s.traces.find(t=>t.message==='reset() · HOME')?.id!==before&&s.robot?.status==='idle'&&s.robot?.currentWaypoint==='HOME';});}
async function until(fn){const start=Date.now();while(!await fn()){if(Date.now()-start>15000)throw Error('UI assertion timeout');await page.waitForTimeout(100);}}
try{
 await page.goto(process.env.CORTEX_TEST_URL??'http://localhost:3000',{waitUntil:'networkidle'});await page.waitForFunction(()=>Number(document.querySelector('canvas')?.dataset.architectureVertices)>100000);await expect(page.locator('.location-stamp')).toContainText('Painted Ladies');expect(JSON.parse(await page.locator('canvas').getAttribute('data-camera'))[2]).toBeCloseTo(1.65,2);await page.waitForTimeout(800);await page.getByRole('button',{name:'Perception',exact:true}).click();await reset();await page.getByRole('button',{name:'Calm voice',exact:false}).click();await until(async()=>(await state()).robot?.status==='moving');await page.waitForTimeout(1800);await page.screenshot({path:'public/media/calm-policy.png',fullPage:true});
 await reset();await page.getByRole('button',{name:'Urgent voice',exact:false}).click();await until(async()=>(await state()).policy.maxSpeed===.9);await page.waitForTimeout(1600);await page.screenshot({path:'public/media/urgent-policy.png',fullPage:true});await page.locator('.viewport').screenshot({path:'public/media/scene.png'});
 await page.keyboard.press('Space');await until(async()=>((await state()).robot?.status==='idle'));await page.getByRole('button',{name:'Visual memory',exact:true}).click();await page.getByRole('button',{name:'Capture scene memory'}).click();await until(async()=>!!(await state()).memory);const captured=(await state()).memory.id;await page.getByRole('button',{name:'Where did you see my backpack?'}).click();await until(async()=>/I saw it beside the planter/.test((await state()).response));expect((await state()).memory.id).toBe(captured);await page.screenshot({path:'public/media/memory.png',fullPage:true});
 await reset();await page.getByRole('button',{name:'Take me there',exact:true}).click();await until(async()=>(await state()).robot?.currentWaypoint==='PLANTER'&&(await state()).robot?.status==='moving');
 await page.getByRole('button',{name:'Event trace',exact:false}).click();await page.waitForTimeout(600);await page.screenshot({path:'public/media/trace.png',fullPage:true});
 await page.keyboard.press('r');await expect(page.locator('main')).toHaveClass('app reality');await page.waitForTimeout(600);expect(await page.locator('.viewport').evaluate(e=>e.getBoundingClientRect().height)).toBeGreaterThan(900);await page.screenshot({path:'public/media/reality.png'});await page.keyboard.press('Space');await until(async()=>((await state()).robot?.status==='idle'));await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Perception',exact:true}).click();await reset();await page.getByRole('button',{name:'Hesitant voice'}).click();await until(async()=>(await state()).pendingConfirmation);await expect(page.getByRole('button',{name:'Yes, approach'})).toBeVisible();await page.getByRole('button',{name:'Stay there'}).click();await until(async()=>((await state()).robot?.status==='idle'));
 await reset();await page.getByRole('button',{name:'Visual memory',exact:true}).click();await page.getByRole('button',{name:'I really need my backpack'}).click();await until(async()=>(await state()).pendingConfirmation);expect((await state()).memory.id).toBe(captured);expect((await state()).policy.personalSpaceMeters).toBe(2);await page.getByRole('button',{name:'Yes, approach'}).click();await until(async()=>(await state()).robot?.status==='moving'&&(await state()).robot?.currentWaypoint==='PLANTER');await page.keyboard.press('Space');await until(async()=>((await state()).robot?.status==='idle'));
 await page.getByTitle('Inspect 3D scene').click();const cameraBefore=await page.locator('canvas').getAttribute('data-camera');const view=await page.locator('canvas').boundingBox();await page.mouse.move(view.x+view.width*.5,view.y+view.height*.5);await page.mouse.down();await page.mouse.move(view.x+view.width*.65,view.y+view.height*.55,{steps:15});await page.mouse.up();await page.waitForTimeout(500);expect(await page.locator('canvas').getAttribute('data-camera')).not.toBe(cameraBefore);await page.locator('.viewport').screenshot({path:'public/media/inspection-3d.png'});await page.getByTitle('Inspect 3D scene').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'public/media/mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await expect(page.getByRole('button',{name:'Connect microphone'})).toBeVisible();
 expect(errors).toEqual([]);await writeFile('docs/browser-results.json',JSON.stringify({passed:true,errors,viewport:[1440,1100],mobile:[390,844],tests:['Volumetric Painted Ladies loaded (>100k vertices), phone camera height 1.65m','calm / urgent controls','camera evidence persisted and retrieved','memory waypoint navigation','Reality keyboard reveal','Space stop in Reality','fearful confirmation cancellation','anxious memory evidence → confirmation → physical navigation','3D camera orbit and parallax','mobile no overflow'],at:new Date().toISOString()},null,2));console.log('Browser tests passed; captures saved.');
}finally{await context.close();await browser.close();}
